CURRENCIES = [
    ("JPY", "Japanese Yen", "¥", 0),
    ("CNY", "Chinese Yuan", "¥", 2),
    ("USD", "US Dollar", "$", 2),
    ("EUR", "Euro", "€", 2),
    ("GBP", "British Pound", "£", 2),
    ("HKD", "Hong Kong Dollar", "HK$", 2),
    ("KRW", "Korean Won", "₩", 0),
    ("TWD", "Taiwan Dollar", "NT$", 2),
    ("SGD", "Singapore Dollar", "S$", 2),
]

EXPENSE_TREE = [
    ("饮食", "🍱", [
        ("外卖", "🛵"),
        ("线下餐饮", "🍜"),
        ("自动贩卖机", "🥤"),
        ("超市", "🥬"),
        ("便利店", "🏪"),
    ]),
    ("交通", "🚇", [
        ("电车地铁", "🚆"),
        ("出租车", "🚕"),
        ("公交", "🚌"),
        ("共享打车", "📱"),
        ("长途", "✈️"),
        ("油费充电", "⛽"),
        ("停车费", "🅿️"),
    ]),
    ("购物", "🛍️", [
        ("生活用品", "🧴"),
        ("服装鞋帽", "👕"),
        ("数码电器", "💻"),
        ("家居家具", "🛋️"),
        ("学习用品", "✏️"),
    ]),
    ("固定账单", "📅", [
        ("会员订阅", "🎬"),
        ("房租", "🏠"),
        ("水电煤网", "💡"),
        ("其他固定账单", "🔁"),
    ]),
    ("服务", "🛎️", [
        ("API", "🔌"),
        ("学费", "🏫"),
        ("课程考试", "🎓"),
        ("邮寄快递", "📦"),
        ("维修", "🔧"),
        ("洗衣干洗", "🧺"),
        ("打印复印", "🖨️"),
        ("证件办理", "🪪"),
    ]),
    ("娱乐", "🎮", [
        ("游戏充值", "🕹️"),
        ("课金打赏", "💖"),
        ("电影演出", "🎭"),
        ("旅行", "🧳"),
        ("展会活动", "🎪"),
        ("KTV酒吧", "🎤"),
    ]),
    ("生活", "🧼", [
        ("美容理发", "💇"),
        ("个护", "🧴"),
        ("看病诊断", "🩺"),
        ("药品", "💊"),
        ("保险", "🛡️"),
    ]),
    ("社交", "🎁", [
        ("红包转账", "🧧"),
        ("请客", "🍻"),
        ("礼物", "🎀"),
    ]),
    # 投资本身不算消费 (买入=转移到持仓); 卖出亏损才记这里, 赚了记 INCOME_TREE 的"投资收益"
    ("投资亏损", "📉", []),
    ("其他", "🗂️", [
        ("未分类", "❓"),
        ("对账调整", "⚖️"),
        ("坏账损失", "📉"),
        ("手续费", "💸"),
    ]),
]

# Income categories live at the top level — when the user is in 收入 mode the
# kind itself implies "income", so wrapping them under another "收入" parent
# is a redundant click. Each entry below becomes its own top-level category.
INCOME_TREE = [
    ("工资", "💼", []),
    ("生活费", "🏠", []),
    ("奖学金", "🎓", []),
    ("红包收入", "🧧", []),
    ("报销", "🧾", []),
    ("退款", "↩️", []),
    ("投资收益", "📈", []),
    ("账户间转账", "🔁", []),
    ("换汇", "💱", []),
    ("其他收入", "✨", []),
]

MERCHANTS = [
    # ── 日本 ──
    # 超市
    ("Life", "超市", "JP"),
    ("OK", "超市", "JP"),
    ("業務スーパー", "超市", "JP"),
    ("イオン", "超市", "JP"),
    ("マルエツ", "超市", "JP"),
    ("西友", "超市", "JP"),
    ("ライフ", "超市", "JP"),
    ("成城石井", "超市", "JP"),
    ("まいばすけっと", "超市", "JP"),
    ("コープ", "超市", "JP"),
    # 便利店
    ("FamilyMart", "便利店", "JP", "ファミマ,全家"),
    ("Lawson", "便利店", "JP", "ローソン,罗森"),
    ("ミニストップ", "便利店", "JP", "MiniStop"),
    ("デイリーヤマザキ", "线下餐饮", "JP"),
    ("NewDays", "线下餐饮", "JP"),
    # 餐饮 - 牛丼/定食
    ("吉野家", "线下餐饮", "JP", "よしのや,Yoshinoya"),
    ("松屋", "线下餐饮", "JP", "Matsuya,まつや"),
    ("すき家", "线下餐饮", "JP", "Sukiya,すきや"),
    ("やよい軒", "线下餐饮", "JP", "Yayoiken"),
    ("大戸屋", "线下餐饮", "JP", "Ootoya"),
    ("ほっともっと", "外卖", "JP", "Hotto Motto,HottoMotto"),
    # 餐饮 - 拉面
    ("一蘭", "线下餐饮", "JP", "Ichiran,一兰"),
    ("一風堂", "线下餐饮", "JP", "Ippudo,一风堂"),
    ("天下一品", "线下餐饮", "JP", "Tenkaippin"),
    ("ラーメン花月嵐", "线下餐饮", "JP"),
    ("日高屋", "线下餐饮", "JP"),
    ("リンガーハット", "线下餐饮", "JP", "Ringer Hut"),
    # 餐饮 - 寿司
    ("スシロー", "线下餐饮", "JP", "Sushiro,寿司郎"),
    ("くら寿司", "线下餐饮", "JP", "Kura Sushi,藏寿司"),
    ("はま寿司", "线下餐饮", "JP", "Hama Sushi,滨寿司"),
    ("かっぱ寿司", "线下餐饮", "JP", "Kappa Sushi,河童寿司"),
    # 餐饮 - 家庭餐厅/居酒屋
    ("ガスト", "线下餐饮", "JP", "Gusto"),
    ("サイゼリヤ", "线下餐饮", "JP", "Saizeriya,萨莉亚"),
    ("ジョナサン", "线下餐饮", "JP", "Jonathan"),
    ("バーミヤン", "线下餐饮", "JP", "Bamiyan"),
    ("デニーズ", "线下餐饮", "JP", "Denny's,丹尼斯"),
    ("ロイヤルホスト", "线下餐饮", "JP", "Royal Host"),
    ("びっくりドンキー", "线下餐饮", "JP", "Bikkuri Donkey"),
    ("CoCo壱番屋", "线下餐饮", "JP", "CoCoIchi,coco壱,壹番屋"),
    ("餃子の王将", "线下餐饮", "JP", "Ohsho,王将"),
    ("大阪王将", "线下餐饮", "JP"),
    ("鳥貴族", "线下餐饮", "JP", "Torikizoku,鸟贵族"),
    ("串カツ田中", "线下餐饮", "JP"),
    # 餐饮 - 快餐
    ("モスバーガー", "线下餐饮", "JP", "Mos Burger,摩斯汉堡"),
    ("ロッテリア", "线下餐饮", "JP", "Lotteria,乐天利"),
    ("バーガーキング", "线下餐饮", "JP", "Burger King,汉堡王"),
    ("サブウェイ", "线下餐饮", "JP", "Subway,赛百味"),
    ("フレッシュネスバーガー", "线下餐饮", "JP", "Freshness Burger"),
    ("ファーストキッチン", "线下餐饮", "JP"),
    # 餐饮 - 烧肉
    ("牛角", "线下餐饮", "JP", "Gyukaku,牛角烧肉"),
    ("焼肉キング", "线下餐饮", "JP", "Yakiniku King"),
    ("安楽亭", "线下餐饮", "JP"),
    ("焼肉ライク", "线下餐饮", "JP", "Yakiniku Like"),
    ("すたみな太郎", "线下餐饮", "JP"),
    # 餐饮 - うどん / そば
    ("丸亀製麺", "线下餐饮", "JP", "Marugame,丸龟制面"),
    ("はなまるうどん", "线下餐饮", "JP", "Hanamaru Udon"),
    ("富士そば", "线下餐饮", "JP", "Fuji Soba,富士荞麦"),
    ("ゆで太郎", "线下餐饮", "JP", "Yudetaro"),
    ("山田うどん", "线下餐饮", "JP"),
    # 餐饮 - とんかつ
    ("かつや", "线下餐饮", "JP", "Katsuya"),
    ("松のや", "线下餐饮", "JP", "Matsunoya"),
    ("とんかつ和幸", "线下餐饮", "JP", "Wako"),
    # 餐饮 - 中華 / その他
    ("幸楽苑", "线下餐饮", "JP"),
    ("ケンタッキー", "线下餐饮", "JP"),
    # 餐饮 - 居酒屋
    ("ワタミ", "线下餐饮", "JP", "Watami,和民"),
    ("笑笑", "线下餐饮", "JP", "Warawara"),
    ("白木屋", "线下餐饮", "JP", "Shirokiya"),
    ("鳥良商店", "线下餐饮", "JP"),
    ("養老乃瀧", "线下餐饮", "JP"),
    ("塚田農場", "线下餐饮", "JP"),
    # 餐饮 - ベーカリー / スイーツ
    ("ミスタードーナツ", "线下餐饮", "JP", "Mister Donut,Mr Donut,ミスド"),
    ("シャトレーゼ", "线下餐饮", "JP", "Chateraise"),
    ("VIE DE FRANCE", "线下餐饮", "JP"),
    # 餐饮 - 外卖
    ("銀のさら", "外卖", "JP"),
    ("Wolt", "外卖", "JP"),
    ("menu", "外卖", "JP"),
    # 咖啡
    ("スターバックス", "线下餐饮", "JP", "Starbucks,星巴克,スタバ"),
    ("ドトール", "线下餐饮", "JP", "Doutor,罗多伦"),
    ("タリーズ", "线下餐饮", "JP", "Tully's,Tullys"),
    ("コメダ珈琲", "线下餐饮", "JP", "Komeda,コメダ"),
    ("サンマルク", "线下餐饮", "JP", "Saint Marc,St Marc"),
    ("PRONTO", "线下餐饮", "JP"),
    ("ベローチェ", "线下餐饮", "JP", "Veloce"),
    # 药妆
    ("マツモトキヨシ", "生活用品", "JP", "Matsumoto Kiyoshi,松本清,マツキヨ"),
    ("ウエルシア", "生活用品", "JP", "Welcia"),
    ("スギ薬局", "生活用品", "JP", "Sugi Drug"),
    ("ココカラファイン", "生活用品", "JP", "Cocokara Fine"),
    ("サンドラッグ", "生活用品", "JP", "Sundrug"),
    ("クスリのアオキ", "生活用品", "JP"),
    # 百货/折扣
    ("ドン・キホーテ", "生活用品", "JP", "Don Quijote,ドンキ,唐吉诃德"),
    ("無印良品", "生活用品", "JP", "MUJI,无印良品,ムジルシ"),
    ("ロフト", "生活用品", "JP", "Loft"),
    ("東急ハンズ", "生活用品", "JP", "Tokyu Hands"),
    # 数码
    ("ヨドバシカメラ", "数码电器", "JP", "Yodobashi,ヨドバシ,友都八喜"),
    ("ビックカメラ", "数码电器", "JP", "Bic Camera,ビック"),
    ("ヤマダ電機", "数码电器", "JP", "Yamada Denki"),
    ("エディオン", "数码电器", "JP"),
    ("ケーズデンキ", "数码电器", "JP"),
    ("ノジマ", "数码电器", "JP"),
    # 服饰
    ("UNIQLO", "服装鞋帽", "JP", "ユニクロ,优衣库"),
    ("GU", "服装鞋帽", "JP", "ジーユー"),
    ("しまむら", "服装鞋帽", "JP", "Shimamura"),
    ("ABCマート", "服装鞋帽", "JP", "ABC Mart"),
    ("ユナイテッドアローズ", "服装鞋帽", "JP"),
    # 家居
    ("ニトリ", "家居家具", "JP", "Nitori,似鸟"),
    ("島忠ホームズ", "家居家具", "JP"),
    # 100 円店
    ("ダイソー", "生活用品", "JP", "Daiso,大创"),
    ("セリア", "生活用品", "JP", "Seria"),
    ("Can Do", "生活用品", "JP", "CanDo,キャンドゥ"),
    ("スリーコインズ", "生活用品", "JP", "3 Coins,3COINS"),
    # 在线/物流
    ("楽天市場", "生活用品", "JP", "Rakuten,乐天市场,乐天"),
    ("Yahoo!ショッピング", "生活用品", "JP", "Yahoo Shopping,雅虎购物"),
    ("メルカリ", "生活用品", "JP", "Mercari"),
    ("ZOZOTOWN", "服装鞋帽", "JP", "Zozo"),
    ("BOOK OFF", "学习用品", "JP"),
    # 书店
    ("紀伊國屋書店", "学习用品", "JP"),
    ("ジュンク堂", "学习用品", "JP"),
    ("三省堂書店", "学习用品", "JP"),
    ("TSUTAYA", "学习用品", "JP"),
    # 交通/出行
    ("JR東日本", "电车地铁", "JP", "JR East,JR东日本"),
    ("東京メトロ", "电车地铁", "JP", "Tokyo Metro,东京地铁"),
    ("都営地下鉄", "电车地铁", "JP", "Toei Subway,都营地铁"),
    ("Suica チャージ", "电车地铁", "JP", "Suica,西瓜卡"),
    ("PASMO チャージ", "电车地铁", "JP", "PASMO"),
    ("出前館", "外卖", "JP", "Demae-can,出前馆"),
    ("GO タクシー", "出租车", "JP", "GO Taxi"),
    # 通信/订阅 (JP)
    ("ドコモ", "水电煤网", "JP", "Docomo,NTT,道科莫"),
    ("au", "水电煤网", "JP", "KDDI"),
    ("ソフトバンク", "水电煤网", "JP", "SoftBank,软银"),
    ("楽天モバイル", "水电煤网", "JP", "Rakuten Mobile,乐天移动"),
    ("東京電力", "水电煤", "JP", "TEPCO,东京电力"),
    ("東京ガス", "水电煤", "JP", "Tokyo Gas,东京煤气"),
    ("NHK", "其他订阅", "JP"),
    ("U-NEXT", "会员订阅", "JP"),
    ("dアニメストア", "会员订阅", "JP"),

    # ── 中国 ──
    # 餐饮 - 火锅
    ("海底捞", "线下餐饮", "CN", "Haidilao"),
    ("巴奴", "线下餐饮", "CN", "Banu"),
    ("呷哺呷哺", "线下餐饮", "CN"),
    ("小龙坎", "线下餐饮", "CN"),
    # 餐饮 - 中餐连锁
    ("西贝", "线下餐饮", "CN", "Xibei"),
    ("绿茶", "线下餐饮", "CN"),
    ("外婆家", "线下餐饮", "CN"),
    ("老乡鸡", "线下餐饮", "CN"),
    ("真功夫", "线下餐饮", "CN"),
    ("永和大王", "线下餐饮", "CN"),
    ("沙县小吃", "线下餐饮", "CN"),
    ("兰州拉面", "线下餐饮", "CN"),
    ("杨国福", "线下餐饮", "CN"),
    ("张亮麻辣烫", "线下餐饮", "CN"),
    # 餐饮 - 快餐
    ("麦当劳", "线下餐饮", "CN", "McDonald's,Maccas"),
    ("肯德基", "线下餐饮", "CN", "KFC,肯爷爷"),
    ("必胜客", "线下餐饮", "CN", "Pizza Hut"),
    ("汉堡王", "线下餐饮", "CN", "Burger King,BK"),
    ("华莱士", "线下餐饮", "CN", "Wallace"),
    # 茶饮/咖啡
    ("喜茶", "线下餐饮", "CN", "HEYTEA"),
    ("奈雪的茶", "线下餐饮", "CN", "Nayuki"),
    ("瑞幸", "线下餐饮", "CN", "Luckin,Luckin Coffee,瑞幸咖啡"),
    ("蜜雪冰城", "线下餐饮", "CN", "MIXUE,蜜雪"),
    ("茶颜悦色", "线下餐饮", "CN", "Chayan"),
    ("古茗", "线下餐饮", "CN"),
    ("沪上阿姨", "线下餐饮", "CN"),
    ("茶百道", "线下餐饮", "CN"),
    ("CoCo都可", "线下餐饮", "CN"),
    ("一点点", "线下餐饮", "CN"),
    ("霸王茶姬", "线下餐饮", "CN", "Chagee"),
    # 烘焙
    ("巴黎贝甜", "线下餐饮", "CN"),
    ("好利来", "线下餐饮", "CN"),
    ("鲍师傅", "线下餐饮", "CN"),
    # 超市
    ("盒马", "超市", "CN", "Hema,盒马鲜生"),
    ("山姆", "超市", "CN", "Sam's Club,SAMS"),
    ("沃尔玛", "超市", "CN", "Walmart"),
    ("永辉", "超市", "CN", "Yonghui"),
    ("大润发", "超市", "CN", "RT-Mart,RT Mart"),
    ("华润万家", "超市", "CN", "Vanguard,华润"),
    ("物美", "超市", "CN"),
    # 便利店
    ("全家", "便利店", "CN", "FamilyMart,Family Mart,ファミマ"),
    ("罗森", "便利店", "CN", "Lawson,LAWSON,ローソン"),
    ("便利蜂", "便利店", "CN"),
    ("美宜佳", "线下餐饮", "CN"),
    # 外卖/打车
    ("美团", "外卖", "CN", "Meituan"),
    ("饿了么", "外卖", "CN", "Eleme"),
    ("滴滴", "共享打车", "CN", "DiDi,Didi"),
    ("高德打车", "共享打车", "CN", "Amap,Gaode"),
    ("曹操出行", "共享打车", "CN"),
    # 长途
    ("12306", "长途", "CN", "铁路12306,China Railway"),
    ("携程", "长途", "CN", "Ctrip,Trip.com"),
    ("飞猪", "长途", "CN", "Fliggy"),
    ("去哪儿", "长途", "CN"),
    ("同程", "长途", "CN"),
    # 电商
    ("淘宝", "生活用品", "CN", "Taobao,淘"),
    ("天猫", "生活用品", "CN", "Tmall"),
    ("京东", "生活用品", "CN", "JD,JD.com,JingDong"),
    ("拼多多", "生活用品", "CN", "PDD,Pinduoduo,Temu"),
    ("唯品会", "生活用品", "CN", "VIP,VIP.com"),
    ("当当", "学习用品", "CN"),
    ("小红书", "生活用品", "CN", "Xiaohongshu,RED,RedNote"),
    ("抖音商城", "生活用品", "CN", "TikTok Shop,Douyin"),
    # 服饰/百货
    ("优衣库", "服装鞋帽", "CN", "UNIQLO,ユニクロ"),
    ("名创优品", "生活用品", "CN", "MINISO"),
    ("屈臣氏", "个护", "CN", "Watsons"),
    # 药店/医疗
    ("大参林", "药品", "CN"),
    ("老百姓药房", "药品", "CN"),
    # 通信
    ("中国移动", "水电煤网", "CN", "China Mobile,移动"),
    ("中国联通", "水电煤网", "CN", "China Unicom,联通"),
    ("中国电信", "水电煤网", "CN", "China Telecom,电信"),
    # 流媒体/订阅
    ("爱奇艺", "会员订阅", "CN", "iQiyi,iQIYI"),
    ("优酷", "会员订阅", "CN", "Youku"),
    ("腾讯视频", "会员订阅", "CN", "Tencent Video,QQ Video"),
    ("哔哩哔哩", "会员订阅", "CN", "Bilibili,B站,bilibili"),
    ("芒果TV", "会员订阅", "CN", "Mango TV"),
    ("网易云音乐", "会员订阅", "CN", "NetEase Music,网易云,网易云音乐"),
    ("QQ音乐", "会员订阅", "CN", "QQ Music"),
    ("喜马拉雅", "会员订阅", "CN"),

    # ── 全球 ──
    # 餐饮连锁
    ("McDonald's", "线下餐饮", "GLOBAL", "麦当劳,マクド,マック,マクドナルド,Maccas"),
    ("KFC", "线下餐饮", "GLOBAL", "肯德基,ケンタッキー,Kentucky"),
    # 便利店 / 零售连锁
    ("7-11", "便利店", "GLOBAL", "セブンイレブン,セブン,7-Eleven,7Eleven,711,7十一"),
    ("IKEA", "家居家具", "GLOBAL", "宜家,イケア"),
    ("Costco", "超市", "GLOBAL", "开市客,コストコ"),
    # 科技 / 数码
    ("Apple", "数码电器", "GLOBAL", "苹果,アップル"),
    ("Google Play", "会员订阅", "GLOBAL", "谷歌,Google"),
    ("Amazon", "数码电器", "GLOBAL", "亚马逊,アマゾン"),
    ("eBay", "生活用品", "GLOBAL", "易贝"),
    ("AliExpress", "生活用品", "GLOBAL", "速卖通,アリエクスプレス"),
    ("Shein", "服装鞋帽", "GLOBAL", "希音"),
    # 游戏
    ("Steam", "游戏充值", "GLOBAL", "蒸汽,Steam商店"),
    ("PlayStation Store", "游戏充值", "GLOBAL", "PS Store,索尼商店,PlayStation"),
    ("Nintendo eShop", "游戏充值", "GLOBAL", "任天堂,ニンテンドー,Nintendo"),
    ("Epic Games", "游戏充值", "GLOBAL", "Epic,EGS"),
    ("GOG", "游戏充值", "GLOBAL", "Good Old Games"),
    # 流媒体
    ("Netflix", "会员订阅", "GLOBAL", "网飞,奈飞,ネトフリ"),
    ("Spotify", "会员订阅", "GLOBAL", "声破天"),
    ("Disney+", "会员订阅", "GLOBAL", "迪士尼,Disney Plus,ディズニープラス"),
    ("HBO Max", "会员订阅", "GLOBAL", "HBO,Max"),
    ("Apple Music", "会员订阅", "GLOBAL", "苹果音乐"),
    ("YouTube Premium", "会员订阅", "GLOBAL", "YouTube,油管"),
    ("Crunchyroll", "会员订阅", "GLOBAL", "クランチロール"),
    ("Twitch", "会员订阅", "GLOBAL", "ツイッチ"),
    # AI / 开发 (商家是付款的公司主体, 产品名进 aliases)
    ("OpenAI", "会员订阅", "GLOBAL", "ChatGPT,GPT,chat gpt,openai.com"),
    ("Anthropic", "会员订阅", "GLOBAL", "Claude,クロード,claude.ai,anthropic.com"),
    ("Google AI", "会员订阅", "GLOBAL", "Gemini,Bard,Google Gemini,Google One"),
    ("GitHub", "会员订阅", "GLOBAL", "Github,Copilot,GitHub Copilot,git"),
    ("Anysphere", "会员订阅", "GLOBAL", "Cursor,cursor.sh"),
    ("Midjourney", "会员订阅", "GLOBAL", "MJ,midjourney.com"),
    ("Perplexity", "会员订阅", "GLOBAL", "perplexity.ai"),
    ("Vercel", "会员订阅", "GLOBAL", "vercel.com"),
    ("Cloudflare", "会员订阅", "GLOBAL", "CF,cloudflare"),
    ("JetBrains", "会员订阅", "GLOBAL", "IntelliJ,PyCharm,WebStorm"),
    # 云盘/工具订阅
    ("iCloud", "会员订阅", "GLOBAL", "苹果云盘"),
    ("Google One", "会员订阅", "GLOBAL", "Google Drive"),
    ("Dropbox", "会员订阅", "GLOBAL", "ドロップボックス"),
    ("Microsoft 365", "会员订阅", "GLOBAL", "Office 365,Office,Microsoft Office"),
    ("Adobe", "会员订阅", "GLOBAL", "PS,Photoshop,Lightroom,Premiere"),
    ("Notion", "会员订阅", "GLOBAL", "ノーション"),
    ("1Password", "会员订阅", "GLOBAL", "1Pass"),
    # 出行 / 旅行
    ("Uber", "共享打车", "GLOBAL", "优步,ユーバー"),
    ("Uber Eats", "外卖", "GLOBAL", "ウーバーイーツ,优食"),
    ("Lyft", "共享打车", "GLOBAL", "莱福特"),
    ("DoorDash", "外卖", "GLOBAL", "ドアダッシュ"),
    ("Airbnb", "旅行", "GLOBAL", "爱彼迎,エアビー"),
    ("Booking.com", "旅行", "GLOBAL", "Booking,缤客"),
    ("Agoda", "旅行", "GLOBAL", "雅高达,アゴダ"),
    # 金融工具
    ("PayPal", "其他订阅", "GLOBAL", "贝宝"),
    ("Wise", "其他订阅", "GLOBAL", "ワイズ,TransferWise"),

    # ── 来自实际使用的补充商家 ──
    ("食堂", "线下餐饮", "JP", "社食,学食"),
    ("しゃぶ葉", "线下餐饮", "JP", "Shabuyo,涮锅叶"),
    ("肉のハナマサ", "超市", "JP", "Hanamasa"),
    ("東京都水道局", "水电煤网", "JP", "东京都水道局,水道"),
    ("pixiv", "会员订阅", "JP", "ピクシブ,FANBOX"),
    ("Apple One", "会员订阅", "GLOBAL", "苹果"),
    ("AppleCare", "会员订阅", "GLOBAL", "苹果"),
    ("微信读书", "会员订阅", "CN", "WeRead"),
    ("FreeCodeCamp", "会员订阅", "GLOBAL", "FCC"),
    ("Anytime", "会员订阅", "JP", "エニタイム,Anytime Fitness,健身房"),
    ("Grok", "会员订阅", "GLOBAL", "xAI"),
    ("AWS", "其他订阅", "GLOBAL", "Amazon Web Services,亚马逊云"),
    ("Google", "API", "GLOBAL", "谷歌,Google Cloud,GCP"),
    ("DeepSeek", "API", "GLOBAL", "深度求索"),
    ("BSG", "游戏充值", "GLOBAL", "Battlestate Games,塔科夫"),
    ("comipo", "课金打赏", "JP", "コミポ"),

    # ── 日本常见商家补充 ──
    # 餐饮
    ("サイゼリヤ", "线下餐饮", "JP", "Saizeriya,萨莉亚"),
    ("ガスト", "线下餐饮", "JP", "Gusto"),
    ("ジョナサン", "线下餐饮", "JP", "Jonathan's"),
    ("バーミヤン", "线下餐饮", "JP", "Bamiyan"),
    ("丸亀製麺", "线下餐饮", "JP", "丸龟制面,Marugame"),
    ("はなまるうどん", "线下餐饮", "JP", "Hanamaru Udon"),
    ("天丼てんや", "线下餐饮", "JP", "Tenya"),
    ("CoCo壱番屋", "线下餐饮", "JP", "CoCo壱,ココイチ,Coco Ichibanya,咖喱"),
    ("餃子の王将", "线下餐饮", "JP", "王将,Ohsho"),
    ("大阪王将", "线下餐饮", "JP", "Osaka Ohsho"),
    ("ケンタッキー", "线下餐饮", "JP", "KFC,肯德基,ケンタ"),
    ("モスバーガー", "线下餐饮", "JP", "MOS Burger,摩斯"),
    ("ロッテリア", "线下餐饮", "JP", "Lotteria"),
    ("フレッシュネスバーガー", "线下餐饮", "JP", "Freshness Burger"),
    ("ドトール", "线下餐饮", "JP", "Doutor"),
    ("コメダ珈琲", "线下餐饮", "JP", "Komeda,コメダ"),
    ("タリーズ", "线下餐饮", "JP", "Tully's"),
    ("サンマルクカフェ", "线下餐饮", "JP", "St. Marc Cafe"),
    ("ミスタードーナツ", "线下餐饮", "JP", "Mister Donut,ミスド"),
    ("鳥貴族", "线下餐饮", "JP", "Torikizoku"),
    ("ワタミ", "线下餐饮", "JP", "Watami,和民"),
    ("磯丸水産", "线下餐饮", "JP", "Isomaru"),
    ("ステーキガスト", "线下餐饮", "JP", "Steak Gusto"),
    ("いきなりステーキ", "线下餐饮", "JP", "Ikinari Steak"),
    ("築地銀だこ", "线下餐饮", "JP", "Gindaco,银章鱼烧"),
    ("かっぱ寿司", "线下餐饮", "JP", "Kappa Sushi,河童寿司"),
    ("はま寿司", "线下餐饮", "JP", "Hama Sushi"),
    ("スターバックス", "线下餐饮", "JP", "Starbucks,星巴克,スタバ"),
    # 超市 / 药妆
    ("業務スーパー", "超市", "JP", "业务超市,Gyomu Super"),
    ("オーケー", "超市", "JP", "OK Store,OK超市"),
    ("ヨークマート", "超市", "JP", "York Mart"),
    ("サミット", "超市", "JP", "Summit"),
    ("マツモトキヨシ", "生活用品", "JP", "Matsukiyo,松本清,マツキヨ"),
    ("ウエルシア", "生活用品", "JP", "Welcia"),
    ("スギ薬局", "生活用品", "JP", "Sugi"),
    ("サンドラッグ", "生活用品", "JP", "Sun Drug"),
    ("ココカラファイン", "生活用品", "JP", "Cocokara Fine"),
    ("ドン・キホーテ", "生活用品", "JP", "唐吉诃德,ドンキ,Don Quijote"),
    # 数码 / 家电 / 杂货
    ("ヨドバシカメラ", "数码电器", "JP", "Yodobashi,友都八喜"),
    ("ビックカメラ", "数码电器", "JP", "Bic Camera"),
    ("ヤマダ電機", "数码电器", "JP", "Yamada Denki"),
    ("ニトリ", "家居家具", "JP", "Nitori,似鸟"),
    ("無印良品", "生活用品", "JP", "MUJI,无印"),
    ("ダイソー", "生活用品", "JP", "Daiso,大创"),
    ("セリア", "生活用品", "JP", "Seria"),
    ("カインズ", "家居家具", "JP", "Cainz"),
    ("ユニクロ", "服装鞋帽", "JP", "UNIQLO,优衣库"),
    ("GU", "服装鞋帽", "JP", "ジーユー"),
    ("しまむら", "服装鞋帽", "JP", "Shimamura"),
    ("ABCマート", "服装鞋帽", "JP", "ABC-MART"),
    # 交通
    ("JR東日本", "电车地铁", "JP", "JR East,JR东日本"),
    ("東京メトロ", "电车地铁", "JP", "Tokyo Metro,东京地铁"),
    ("都営地下鉄", "电车地铁", "JP", "Toei,都营"),
    ("小田急", "电车地铁", "JP", "Odakyu"),
    ("東急", "电车地铁", "JP", "Tokyu"),
    ("京王", "电车地铁", "JP", "Keio"),
    ("ENEOS", "油费充电", "JP", "エネオス,新日石"),
    ("出光", "油费充电", "JP", "Idemitsu"),
    ("タイムズ", "停车费", "JP", "Times,タイムズパーキング"),
    # 书籍 / 娱乐 / 服务
    ("紀伊國屋書店", "学习用品", "JP", "Kinokuniya,纪伊国屋"),
    ("TSUTAYA", "学习用品", "JP", "蔦屋"),
    ("ブックオフ", "学习用品", "JP", "BOOKOFF,Book Off"),
    ("ヨドバシ.com", "数码电器", "JP", "Yodobashi.com"),
    ("カラオケ館", "KTV酒吧", "JP", "Karaokekan"),
    ("ビッグエコー", "KTV酒吧", "JP", "Big Echo"),
    ("ラウンドワン", "电影演出", "JP", "Round1"),
    ("TOHOシネマズ", "电影演出", "JP", "TOHO Cinemas,东宝影院"),
    ("郵便局", "邮寄快递", "JP", "日本邮便,Japan Post,ゆうパック"),
    ("クロネコヤマト", "邮寄快递", "JP", "Yamato,黑猫宅急便,宅急便"),
]
